<?php
/*function cgc_reg_form_alter(&$form, &$form_state, $form_id) {
	dpm($form);
	dpm($form_state);
	dpm($form_id);
}*/

function cgc_reg_form_camp_common_ground_registration_entityform_edit_form_alter(&$form, &$form_state, $form_id) {
//	dpm($form_state);
//	dpm($form_id);
	$form['field_attendees'][und][add_more]['#value'] = t('Add another attendee');
	$form['field_attendees'][und][0][remove_button]['#value'] = t('Delete this attendee');
	$form['field_phone'][und][add_more]['#value'] = t('Add another number');
//	dpm($form);
}
